# Generated by Django 3.1.7 on 2021-04-15 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210414_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('country_ru', models.CharField(max_length=50, null=True)),
                ('country_en', models.CharField(max_length=50, null=True)),
                ('country_fr', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('city_ru', models.CharField(max_length=50, null=True)),
                ('city_en', models.CharField(max_length=50, null=True)),
                ('city_fr', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('district_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('district_en', models.CharField(blank=True, max_length=50, null=True)),
                ('district_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('region_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('region_en', models.CharField(blank=True, max_length=50, null=True)),
                ('region_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(max_length=50)),
                ('street_ru', models.CharField(max_length=50, null=True)),
                ('street_en', models.CharField(max_length=50, null=True)),
                ('street_fr', models.CharField(max_length=50, null=True)),
                ('corps', models.CharField(blank=True, max_length=50)),
                ('corps_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('corps_en', models.CharField(blank=True, max_length=50, null=True)),
                ('corps_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('link', models.URLField(unique=True)),
                ('organizers', models.CharField(max_length=100)),
                ('additional_information', models.CharField(blank=True, max_length=500)),
                ('main_image', models.ImageField(upload_to='events/')),
                ('background_image', models.ImageField(upload_to='events/')),
                ('list_of_dates', models.JSONField()),
                ('tag', models.ManyToManyField(to='catalog.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('link', models.URLField(unique=True)),
                ('organizers', models.CharField(max_length=100)),
                ('additional_information', models.CharField(blank=True, max_length=500)),
                ('main_image', models.ImageField(upload_to='events/')),
                ('background_image', models.ImageField(upload_to='events/')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.address')),
                ('tag', models.ManyToManyField(to='catalog.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealLifeEvent',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.place')),
                ('list_of_dates', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('catalog.place',),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
