# Generated by Django 3.1.7 on 2021-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210415_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineevent',
            name='additional_information_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='additional_information_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='additional_information_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='organizers_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='organizers_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='organizers_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='short_description_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='short_description_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='additional_information_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='additional_information_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='additional_information_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='organizers_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='organizers_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='organizers_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onlineevent',
            name='background_image',
            field=models.ImageField(default='img_not_found_bg', upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='onlineevent',
            name='main_image',
            field=models.ImageField(default='img_not_found', upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='background_image',
            field=models.ImageField(default='img_not_found_bg', upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.ImageField(default='img_not_found', upload_to='events/'),
        ),
    ]
