# Generated by Django 3.1.7 on 2021-04-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210415_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='onlineevent',
            options={'verbose_name': 'Online Event', 'verbose_name_plural': 'Online Events'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='reallifeevent',
            options={'verbose_name': 'Real Life Event', 'verbose_name_plural': 'Real Life Events'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
