# Generated by Django 3.1.7 on 2021-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210415_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='corps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
