# Generated by Django 3.1.7 on 2021-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210415_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
