# Generated by Django 3.2 on 2021-04-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210415_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineevent',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='tag',
            new_name='tags',
        ),
    ]
